<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ResenjeService"
	targetNamespace="http://demo.example.com/ws/resenje"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://demo.example.com/ws/resenje"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns="http://demo.example.com/ws/resenje"
			attributeFormDefault="unqualified" elementFormDefault="unqualified"
			targetNamespace="http://demo.example.com/ws/resenje">
			<xs:element name="createResenje" type="xs:string" />
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="createResenje">
		<wsdl:part name="createResenje" element="tns:createResenje">
		</wsdl:part>
	</wsdl:message>
	<wsdl:portType name="Resenje">
		<wsdl:operation name="createResenje">
			<wsdl:input name="createResenje" message="tns:createResenje">
			</wsdl:input>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ResenjeServiceSoapBinding"
		type="tns:Resenje">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="createResenje">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="createResenje">
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ResenjeService">
		<wsdl:port name="ResenjePort"
			binding="tns:ResenjeServiceSoapBinding">
			<soap:address
				location="http://localhost:8081/ResenjePort" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
